### PR TITLE
Fix error handler

### PR DESCRIPTION
**Pull request by tmteamz**

### CODE REVIEW

**Comment by TooTallNate** [comment]
What does this fix exactly?

**Comment by knoxcard** [comment]
@TooTallNate - the program immediately terminates (throw instead of return) upon an error while connecting to the host?  @tmteamz's pull request perhaps allows for connection retries?

**Comment by tmteamz** [comment]
@knoxcard I try to catch the error and it didn't work. so i lookup in the socks-proxy-agent code and edit that part.

**Comment by TooTallNate** [comment]
You should attach an `error` event listener to the http.Request object in order to catch these errors.

**Comment by tmteamz** [comment]
it didn't work for me
```javascript
https.get(opts, function (res) {
  console.log('"response" event!', res.headers);
  res.pipe(process.stdout);
}).on('error', (e) => {
  console.error(e);
});
```

**Comment by tmteamz** [comment]
I'm gonna close this PR because i just realize that didn't fix the problem

**Pull request closed without merging**
