### PR TITLE
use opts.host instead of host

### LINKED ISSUE #62: upgrade to 5.0.1 breaks old code
node version: v16.3.0

old working code (5.0.0)
``` Javascript
agent: new SocksProxyAgent('socks5://127.0.0.1:9050');
```

error:
```(node:1431) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error: write EPROTO 139806041069504:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
  errno: -71,
  code: 'EPROTO',
  syscall: 'write'
}
```
after using 5.0.0 it works again.

### PR DESCRIPTION
**Pull request by jumoog**
fixes #62

### CODE REVIEW

**Comment by Kikobeats** [comment]
In which scenarios `servername` would be null/undefined?

**Comment by jumoog** [comment]
it's not null but it's the IP Adress. You can't use a IP Adress for a Hostname

**Comment by Kikobeats** [comment]
The warning is still there

https://github.com/TooTallNate/node-socks-proxy-agent/runs/2932280799#step:7:10

**Comment by jumoog** [comment]
Okay, I'll keep looking. But with this change my code runs again.

**Comment by jumoog** [comment]
should split it in to PRs?

**Comment by Kikobeats** [comment]
yea, split into two tests please!

**Comment by jumoog** [comment]
Okay now I know what happens. Without opts.host the IP address is used and then when I try to connect HTTPS an openssl error occurs and the program crashes. Because of the crash also appears the warning DEP0123

**Pull request merged**
