### PR TITLE
Proxy-authentication

### LINKED ISSUE #21: SOCKS5 authentication failed
Hello, I tried to connect to proxy with node-socks-proxy-agent.

My config:

```
new SocksProxyAgent({
  host: '127.0.0.1',
  port: 1080,
  protocol: 'socks:',
  auth: 'username:password'
});
```
And I getting error: `Socks5 Authentication failed`

I see logs in my proxy-server:

```
error after reading 7 bytes in 0 seconds: could not access user ""'s records in the system password file: no system error
```

### PR DESCRIPTION
**Pull request by tynopet**
I want to resolve #21

### CODE REVIEW

**Comment by knoxcard** [comment]
Any update on this?

**Comment by S0c5** [comment]
Please merge this PR!

**Comment by TooTallNate** [comment]
Thank you! Sorry for the delay.

**Comment by marook** [comment]
Do you plan to release a v4.0.2 with this fix?

**Pull request merged**
