### PR TITLE
Refactor to use `socks-client` module instead of `rainbowsocks`

### PR DESCRIPTION
**Pull request by TooTallNate**
For socks v5 support!

/cc @andyhu Let me know if you have any comments before I merge.

### CODE REVIEW

**Comment by TooTallNate** [comment]
Supersedes #3.

**Comment by andyhu** [comment]
Hmm, I didn't thought about `socks4a://` as the proxy scheme, it looks a bit weird. Anyway if you would like to support it this PR we need to change this PR as well TooTallNate/node-proxy-agent#5

**Comment by TooTallNate** [comment]
Ultimately I like `node-proxy-agent` to support all the curl-supported proxy formats:

```
PROXY PROTOCOL PREFIXES
       Since  curl  version  7.21.7,  the proxy string may be specified with a
       protocol:// prefix to specify alternative proxy protocols.

       If no protocol is specified in  the  proxy  string  or  if  the  string
       doesn't  match  a  supported  one, the proxy will be treated as an HTTP
       proxy.

       The supported proxy protocol prefixes are as follows:

       socks4://
              Makes it the equivalent of --socks4

       socks4a://
              Makes it the equivalent of --socks4a

       socks5://
              Makes it the equivalent of --socks5

       socks5h://
              Makes it the equivalent of --socks5-hostname
```

**Comment by andyhu** [comment]
Well that makes sense. But I guess `socks5h` should work the same as scoks5 right? I tested to use `socks://localhost:1080` instead of `socks://127.0.0.1:1080`, it also works

**Comment by TooTallNate** [comment]
I think it means something different: like one means the hostname is resolved on the client, and the other means the hostname is resolved on the server. I'm not sure if `socks-client` supports this currently or not.

**Comment by andyhu** [comment]
By the way, regarding to the authentication, socks4 seems also support a userid to be passed as parameter. It is not quite secure though.
Also the only difference between `socks4` and `socks4a` seems that socks4a can resolve the host name in the proxy url while in socks4 only ip address is allowed

**Comment by TooTallNate** [comment]
Found a relevant article: http://blog.sanctum.geek.nz/ssh-socks-and-curl/

> This not only tunnels our HTTP request through to remote.example.com and returns any response, it does the DNS lookup on the other end too. This means we can not only retrieve documents from remote servers, we can resolve their hostnames too, even if our client side can’t contact the appropriate DNS server on its own. This is what the h suffix does in the socks5h:// URI syntax above.

**Comment by TooTallNate** [comment]
We probably need to implement some client-side DNS resolution logic for `4` it sounds like.

**Comment by TooTallNate** [comment]
It was a bit hard to find an explanation on the difference between `5` and `5h`: http://unix.stackexchange.com/a/175891

**Comment by andyhu** [comment]
Yes, I found it a bit confusing and lack of documentations. As for my understanding (please correct me if I'm wrong), when mentioning `resolve the hostname` for `socks4a` and `socks5h` proxy they really mean to resolve the http requests' host name but not the one in proxy's url right? If that's the case, I guess we could just ignore it and let the proxy to handle it? Since the socks driver has nothing to do with it, curl is actually a client which is able to resolve host name locally, but superagent-proxy driver shouldn't. They don't touch any data passed trough it. And actually socks driver can't do anything about resolving host names. If they are resolved ip addresses, socks server will not get the correct host name to request resources.
What do you think?

**Comment by TooTallNate** [comment]
Well, curl is a client, just like node is. And node can do DNS lookups with its `dns` module, so we do actually need to implement some logic for this here. I actually just finished implementing that in 2d58dce
if you want to take a peek.

**Comment by JoshGlazebrook** [comment]
Just want to let you guys know that I recently was granted ownership of the "socks" package and I will be migrating my "socks-client" package to there in the future. I will be leaving the "socks-client" up on npm so it shouldn't cause any issues with anything already using it but for future versions I will be publishing to "socks".

**Pull request merged**
